trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  serviceConnection: 'Terraform'   # Azure RM service connection name
  tfWorkingDir: '$(System.DefaultWorkingDirectory)/terraform'

steps:
- checkout: https://github.com/rakeshjalagam776/Terraform-Tasks/
  persistCredentials: true

- task: AzureCLI@2
  displayName: 'Login to Azure'
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Logged in to Azure with service connection"

- script: |
    curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
    unzip terraform.zip
    sudo mv terraform /usr/local/bin/
    terraform -version
  displayName: 'Install Terraform'

- script: |
    cd $(tfWorkingDir)
    terraform init
  displayName: 'Terraform Init'

- script: |
    cd $(tfWorkingDir)
    terraform validate
  displayName: 'Terraform Validate'

- script: |
    cd $(tfWorkingDir)
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'

- script: |
    cd $(tfWorkingDir)
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'

- script: |
    cd $(tfWorkingDir)
    terraform output
  displayName: 'Show Terraform Outputs'
